/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fomre;

import forme.model.ModelTabeleKorisnik;
import forme.model.ModelTabelePoruka;
import java.awt.Point;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import model.Poruka;
import model.User;
import niti.NitAktivniKorisnici;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Jovana
 */
public class KlijentskaForma extends javax.swing.JFrame {
    private User u;
    /**
     * Creates new form KlijentskaForma
     */
    public KlijentskaForma(User u) {
        this.u=u;
        initComponents();
        popuniTabelu();
        //
        NitAktivniKorisnici nit1 = new NitAktivniKorisnici(this);
        nit1.start();
        //
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonPOSALJI_SVIMA = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePOSLEDNJE3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableSVEPORUKE = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonPOSALJI_JEDNOJ_OSOBI = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("poruka");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButtonPOSALJI_SVIMA.setText("posalji svima");
        jButtonPOSALJI_SVIMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPOSALJI_SVIMAActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel2.setText("Prikaz korisnika koji su prijavljeni");

        jTablePOSLEDNJE3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablePOSLEDNJE3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePOSLEDNJE3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTablePOSLEDNJE3);

        jTableSVEPORUKE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableSVEPORUKE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSVEPORUKEMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableSVEPORUKE);

        jLabel3.setText("poslednje 3 pristigle poruke");

        jLabel5.setText("sve poruke");

        jButtonPOSALJI_JEDNOJ_OSOBI.setText("posalji jednoj osobi");
        jButtonPOSALJI_JEDNOJ_OSOBI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPOSALJI_JEDNOJ_OSOBIActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ODJAVA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(398, 398, 398))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonPOSALJI_SVIMA)
                                    .addComponent(jButtonPOSALJI_JEDNOJ_OSOBI))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonPOSALJI_SVIMA)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonPOSALJI_JEDNOJ_OSOBI))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(89, 89, 89)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPOSALJI_SVIMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPOSALJI_SVIMAActionPerformed
        String text = jTextArea1.getText().trim();
        Poruka p = new Poruka(0, u, null, new Date(), text);
        KlijentskiZahtev kz = new KlijentskiZahtev(p, operacije.Operacije.POSALJI_SVIMA);
        komunikacija.Komunikacija.getInstance().posaljiZahtev(kz);
        //
        ServerskiOdgovor so = komunikacija.Komunikacija.getInstance().primiOdgovor();
        boolean uspeh = (boolean) so.getOdgovor();
        if(uspeh){
            JOptionPane.showMessageDialog(null, "USPSENO STE POSLALI PORUKU SVIMA");
        }else{
            JOptionPane.showMessageDialog(null, "NISTE USPSENO POSLALI PORUKU SVIMA");
        }
                
    }//GEN-LAST:event_jButtonPOSALJI_SVIMAActionPerformed

    private void jButtonPOSALJI_JEDNOJ_OSOBIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPOSALJI_JEDNOJ_OSOBIActionPerformed
        int red = jTable1.getSelectedRow();
        if(red==-1){
            JOptionPane.showMessageDialog(null, "NISTE SELEKTOVALI KORISNIKA");
            return;
        }
        ModelTabeleKorisnik mtk = (ModelTabeleKorisnik) jTable1.getModel();
        User primalac = mtk.getLista().get(red);
        String text = jTextArea1.getText().trim();
        //posiljalac - u
        Poruka p = new Poruka(0, u, primalac, new Date(), text);
        KlijentskiZahtev kz = new KlijentskiZahtev(p, operacije.Operacije.POSALJI_JEDNOM_KORISNIKU);
        komunikacija.Komunikacija.getInstance().posaljiZahtev(kz);
        //
        ServerskiOdgovor so = komunikacija.Komunikacija.getInstance().primiOdgovor();
        boolean uspeh = (boolean) so.getOdgovor();
        if(uspeh)
            JOptionPane.showMessageDialog(null, "USPESNO POSLATA PORUKA");
        else
            JOptionPane.showMessageDialog(null, "NIJE USPESNO POSLATA PORUKA");
    }//GEN-LAST:event_jButtonPOSALJI_JEDNOJ_OSOBIActionPerformed

    private void jTablePOSLEDNJE3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePOSLEDNJE3MouseClicked
        //prikazi celu poruku
        JTable tabela = (JTable) evt.getSource();
        Point point= evt.getPoint();
        int red = tabela.rowAtPoint(point);
        ModelTabelePoruka mtp = (ModelTabelePoruka) jTablePOSLEDNJE3.getModel();
        String text = mtp.getLista().get(red).getTekst();
        JOptionPane.showMessageDialog(null, text);
        
    }//GEN-LAST:event_jTablePOSLEDNJE3MouseClicked

    private void jTableSVEPORUKEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSVEPORUKEMouseClicked
         //prikazi celu poruku
        JTable tabela = (JTable) evt.getSource();
        Point point= evt.getPoint();
        int red = tabela.rowAtPoint(point);
        ModelTabelePoruka mtp = (ModelTabelePoruka) jTableSVEPORUKE.getModel();
        String text = mtp.getLista().get(red).getTekst();
        JOptionPane.showMessageDialog(null, text);
        
    }//GEN-LAST:event_jTableSVEPORUKEMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        KlijentskiZahtev kz = new KlijentskiZahtev(u, operacije.Operacije.ODJAVA_KLIJENT);
        komunikacija.Komunikacija.getInstance().posaljiZahtev(kz);
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonPOSALJI_JEDNOJ_OSOBI;
    private javax.swing.JButton jButtonPOSALJI_SVIMA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTablePOSLEDNJE3;
    private javax.swing.JTable jTableSVEPORUKE;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    public void popuniTabelu() {
        KlijentskiZahtev kz = new KlijentskiZahtev(null, operacije.Operacije.VRATI_ULOGOVANE);
        komunikacija.Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so =   komunikacija.Komunikacija.getInstance().primiOdgovor();
        
        List<User> lista = (List<User>) so.getOdgovor();
        lista.remove(u);
        ModelTabeleKorisnik mtk = new ModelTabeleKorisnik(lista);
        jTable1.setModel(mtk);
    }
    public void popuniTabelePoruke() {
        KlijentskiZahtev kz = new KlijentskiZahtev(u, operacije.Operacije.VRATI_PORUKE_ODBRANOG_KLIJENTA);
        komunikacija.Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so =   komunikacija.Komunikacija.getInstance().primiOdgovor();
        
        List<Poruka> listaSVIHPORUKA = (List<Poruka>) so.getOdgovor();
        
        if(listaSVIHPORUKA.size()>=4){
            //sve poruke osim poslednje 3
            ModelTabelePoruka mtp = new ModelTabelePoruka(listaSVIHPORUKA.subList(0, listaSVIHPORUKA.size()-4));
            jTableSVEPORUKE.setModel(mtp);

            //POSLEDNJE TRI
            ModelTabelePoruka mtp2 = new ModelTabelePoruka(listaSVIHPORUKA.subList(listaSVIHPORUKA.size()-3, listaSVIHPORUKA.size()));
            jTablePOSLEDNJE3.setModel(mtp2);
        }
        else{
            ModelTabelePoruka mtp3 = new ModelTabelePoruka(listaSVIHPORUKA);
            jTablePOSLEDNJE3.setModel(mtp3);
            jTableSVEPORUKE.setModel(mtp3);
        }
    }

    public void proveriDaLiJeKorisnikOdjavljenOdStraneServera() {
        KlijentskiZahtev kz= new KlijentskiZahtev(null, operacije.Operacije.ODJAVA_OD_STRANE_SERVERA);
        komunikacija.Komunikacija.getInstance().posaljiZahtev(kz);
        //
        ServerskiOdgovor so = komunikacija.Komunikacija.getInstance().primiOdgovor();
        boolean odjavljen = (boolean) so.getOdgovor();
        if(odjavljen){
            JOptionPane.showMessageDialog(null, "Odjavljeni ste od strane servera");
            System.exit(0);
        }
    }
}
