/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import forme.model.ModelTabeleKorisnik;
import forme.model.ModelTabelePoruka;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import model.Admin;
import model.Poruka;
import model.User;
import niti.NitSviKorisnici;
import server.PokreniServer;

/**
 *
 * @author Jovana
 */
public class ServerskaForma extends javax.swing.JFrame {
    private Admin admin;
    private PokreniServer ps;
    int offset = 0;
    /**
     * Creates new form ServerskaForma
     */
    public ServerskaForma(Admin admin) {
        this.admin=admin;
        initComponents();
        jButtonZAUSTAVI.setEnabled(false);
        //
        ModelTabelePoruka mtp = new ModelTabelePoruka(new ArrayList<>());
        jTablePORUKE.setModel(mtp);
        //
       popuniTabeluKorisnici();
       //pokreni nit
        NitSviKorisnici nit1 = new NitSviKorisnici(this);
        nit1.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButtonZAUSTAVI = new javax.swing.JButton();
        jButtonUnesiKorisnika = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePORUKE = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableKLIJENTI = new javax.swing.JTable();
        jToggleButtonODJAVI_KORISNIKA = new javax.swing.JToggleButton();

        jLabel1.setText("jLabel1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jButton1.setText("porkeni server");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonZAUSTAVI.setText("zaustavi server i odjavi sve korisnike");
        jButtonZAUSTAVI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZAUSTAVIActionPerformed(evt);
            }
        });

        jButtonUnesiKorisnika.setText("unesi korisnika");
        jButtonUnesiKorisnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUnesiKorisnikaActionPerformed(evt);
            }
        });

        jButton2.setText("prikazi sve poruke");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTablePORUKE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablePORUKE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePORUKEMouseClicked(evt);
            }
        });
        jTablePORUKE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTablePORUKEKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePORUKE);

        jLabel2.setText("Poruke");

        jLabel3.setText("Korisnici");

        jTableKLIJENTI.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableKLIJENTI);

        jToggleButtonODJAVI_KORISNIKA.setText("odjavi korisnika");
        jToggleButtonODJAVI_KORISNIKA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonODJAVI_KORISNIKAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(43, 43, 43)
                            .addComponent(jButton2))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jToggleButtonODJAVI_KORISNIKA, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonZAUSTAVI)
                        .addGap(34, 34, 34)
                        .addComponent(jButtonUnesiKorisnika)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButtonZAUSTAVI)
                    .addComponent(jButtonUnesiKorisnika))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jToggleButtonODJAVI_KORISNIKA))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       ps=new PokreniServer();
       ps.start();
       jButtonZAUSTAVI.setEnabled(true);
       jButton1.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonZAUSTAVIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZAUSTAVIActionPerformed
        //odjavi sve klijente ako ima nekog prijavljenog
        if( !controller.Controller.getInstance().getUlogovaniKorisnici().isEmpty()){
             controller.Controller.getInstance().odjaviSveKlijente();
        }
        ps.zaustavi();
        jButtonZAUSTAVI.setEnabled(false);
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jButtonZAUSTAVIActionPerformed

    private void jButtonUnesiKorisnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUnesiKorisnikaActionPerformed
        UnesiKorisnika uk = new UnesiKorisnika(this, true);
        uk.setVisible(true);
    }//GEN-LAST:event_jButtonUnesiKorisnikaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     //uzmi sve poruke iz baze 
     offset=0;
        popuniTabelu();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTablePORUKEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePORUKEMouseClicked
        JTable tabela = (JTable) evt.getSource();
        Point point = evt.getPoint();
        int red = tabela.rowAtPoint(point);
        List<Poruka> lista =((ModelTabelePoruka) jTablePORUKE.getModel()).getLista();
        Poruka p = lista.get(red);
        JOptionPane.showMessageDialog(null, p.getTekst());
    }//GEN-LAST:event_jTablePORUKEMouseClicked

    private void jTablePORUKEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTablePORUKEKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           offset+=5;
            popuniTabelu();
        }
        
    }//GEN-LAST:event_jTablePORUKEKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            offset+=5;
            popuniTabelu();
            
        }
    }//GEN-LAST:event_formKeyPressed

    private void jToggleButtonODJAVI_KORISNIKAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonODJAVI_KORISNIKAActionPerformed
        //vidi koji korisnik je selektovan
        int red= jTableKLIJENTI.getSelectedRow();
        if(red==-1){
            JOptionPane.showMessageDialog(null, "GRESKA NISTE SELEKTOVALI KORISNIKA");
            return;
        }
        ModelTabeleKorisnik mtk = (ModelTabeleKorisnik) jTableKLIJENTI.getModel();
        User korisnik = mtk.getLista().get(red);
        //ako nije aktivan ne mogu da ga odjavim
        if(!controller.Controller.getInstance().getUlogovaniKorisnici().contains(korisnik)){
            JOptionPane.showMessageDialog(null, "Izabran korisnik nije prijaljen na sistem");
            return;
        }
        //izabranom korisniku posalji poruku
        controller.Controller.getInstance().odjaviKorisnika(korisnik);
    }//GEN-LAST:event_jToggleButtonODJAVI_KORISNIKAActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonUnesiKorisnika;
    private javax.swing.JButton jButtonZAUSTAVI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableKLIJENTI;
    private javax.swing.JTable jTablePORUKE;
    private javax.swing.JToggleButton jToggleButtonODJAVI_KORISNIKA;
    // End of variables declaration//GEN-END:variables

    private void popuniTabelu() {
        List<Poruka> poruke = controller.Controller.getInstance().ucitajSvePoruke(offset);
        System.out.println("Offset: " + offset);
        ModelTabelePoruka mtp = new ModelTabelePoruka(poruke);
        jTablePORUKE.setModel(mtp);
        
    }

    public void popuniTabeluKorisnici() {
         List<User> sviKorisnici = controller.Controller.getInstance().vratiSveKorisnike();
        ModelTabeleKorisnik mtk = new ModelTabeleKorisnik(sviKorisnici);
        jTableKLIJENTI.setModel(mtk);
    }
}
